name = "AbstractNFFTs"
uuid = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.8.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.6"
