name = "AbstractNFFTs"
uuid = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
author = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.2.1"

[deps]
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
Graphics = "0.4, 1.0"